### ISSUE TITLE
Concurrently Write/Read

### ISSUE THREAD

**Issue by szbk** [virgel1995/bad.db#1]
Does it support reading and writing files simultaneously?

**Comment by sabrydawood** [comment]
Yes, it can support reading and writing at the same time

**Comment by szbk** [comment]
I think I asked the question wrong. What I want to ask is whether multiple users can write or read at the same time?

**Comment by sabrydawood** [comment]
It's support it but I forget to try an example
You can try it

**Comment by sabrydawood** [comment]
If you have any issue please tell to fix 
I didn't have time now to maintain this module 
But I will fix problems as soon as I can
